CREATE TABLE companies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_number VARCHAR(512),
    org_number_index BYTEA UNIQUE,
    company_name VARCHAR(512),
    authorized_signatory VARCHAR(512)
);

CREATE TABLE case_workers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(512),
    email VARCHAR(512),
    email_index BYTEA UNIQUE,
    password VARCHAR(255)
);

CREATE TABLE applications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INT REFERENCES companies(id),
    requested_amount VARCHAR(512),
    purpose TEXT,
    status VARCHAR(30) DEFAULT 'PENDING_DOCS',
    decision VARCHAR(20),
    decision_reason TEXT,
    scoring_result TEXT,
    audit_log TEXT DEFAULT '[]',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
    uuid uuid PRIMARY KEY,
    application_id INT REFERENCES applications(id),
    filename VARCHAR(512),
    doc_type VARCHAR(50),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
